### ISSUE TITLE
Incandescence lava shader

### ISSUE THREAD

**Issue by gajop** [The-Yak/lavashader#1]
Hm, I wanted to make a fast PR today, but I've noticed that the version on github is different than what's available in this map.
Here are the changes: http://pastie.org/private/ylj4c39tlfgdmtwybp38yg
Most of my changes are in the 413-469 range, so I guess the majority of differences is just an old version.. Can you confirm?
Should I base my changes entirely on the gitbub version?

**Comment by The-Yak** [comment]
Github version is latest version that I have worked upon.

It appears qray has modified the lava shader code to add lava pits with more explosions and custom geovent cegs. The lava pits only work with Incandescence's heightmap, the geovent cegs are nice but IMO should be a separate gadget.

Given that, I'd say base your changes upon github version.

**Comment by gajop** [comment]
Alright, is there any map that uses the github version so I'd be able to
properly test the changes?

**Comment by The-Yak** [comment]
violence 4.1 uses latest github version minus 1 bugfix(error related to lavalevel). Drop your updated lava.lua in and it should be fine.
